### ISSUE TITLE
date() expects parameter 2 to be long, string given

### ISSUE THREAD

**Issue by jereze** [getkirby-v2/feed-plugin#4]
Hello,

I get the error `date() expects parameter 2 to be long, string given` after upgrading to Kirby 2.4.1. (I was in 2.3.X before).

Error in `template.php`:
```
    <lastBuildDate><?php echo date('r', $modified) ?></lastBuildDate>
```

**Comment by jereze** [comment]
Related discussion: https://forum.getkirby.com/t/problem-with-lastbuilddate-from-feed-plugin/1822/3

**Comment by peterkelm** [comment]
I fixed this by changing the first parameter of date() in `feed/feed.php` (line 40) to `null` instead of `false`. I.e.

`$options['modified'] = $items->first()->date(null, $options['datefield']);`
